# Generated by Django 5.1.2 on 2025-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guestsession_systemsetting_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['category', 'key']},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, help_text='Text for action button', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='Optional URL for notification action', null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(default='general', help_text='Category for organizing settings', max_length=50),
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='app',
            field=models.CharField(choices=[('crm', 'CRM System'), ('inventory', 'Inventory Management'), ('shop', 'Shop Management'), ('website', 'Website Management'), ('blog', 'Blog Management'), ('hr', 'HR Management'), ('admin', 'Admin Panel'), ('quotes', 'Quote Management'), ('financial', 'Financial Data'), ('reports', 'Reporting System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('quote', 'Quote Update')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('blogger', 'Blogger'), ('employee', 'Employee'), ('sales_rep', 'Sales Representative'), ('sales_manager', 'Sales Manager'), ('blitzhub_admin', 'BlitzHub Admin'), ('it_admin', 'IT Admin')], default='customer', max_length=20),
        ),
    ]
