# Generated by Django 5.1.2 on 2025-06-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_profile_discovery',
            field=models.BooleanField(default=True),
        ),
    ]
