# Generated by Django 5.1.2 on 2025-08-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='location',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity that can be ordered internally'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('meter', 'Meters'), ('kg', 'Kilograms'), ('liter', 'Liters'), ('box', 'Box'), ('set', 'Set'), ('roll', 'Roll'), ('pack', 'Pack')], default='pcs', help_text='Unit of measurement for this product', max_length=10),
        ),
    ]
