# Generated by Django 5.1.2 on 2025-06-03 20:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_scoring_enabled', models.BooleanField(default=True)),
                ('auto_assign_leads', models.BooleanField(default=False)),
                ('default_followup_days', models.IntegerField(default=7)),
                ('followup_reminder_hours', models.IntegerField(default=24)),
                ('analytics_retention_days', models.IntegerField(default=365)),
                ('email_notifications', models.BooleanField(default=True)),
                ('overdue_followup_alerts', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CRM Settings',
                'verbose_name_plural': 'CRM Settings',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, help_text='e.g., 1-10, 11-50, 51-200, 200+', max_length=50, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Zimbabwe', max_length=100)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('client', 'Active Client'), ('inactive', 'Inactive'), ('lost', 'Lost')], default='lead', max_length=50)),
                ('customer_type', models.CharField(choices=[('walk_in', 'Walk-in Customer'), ('corporate', 'Corporate Client'), ('institutional', 'Institutional Client'), ('government', 'Government Client'), ('reseller', 'Reseller/Partner')], default='walk_in', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('vip', 'VIP Client')], default='medium', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Credit limit in USD', max_digits=12)),
                ('payment_terms', models.IntegerField(default=30, help_text='Payment terms in days')),
                ('tax_number', models.CharField(blank=True, help_text='VAT/Tax registration number', max_length=50, null=True)),
                ('currency_preference', models.CharField(choices=[('USD', 'US Dollar'), ('ZWG', 'Zimbabwe Gold')], default='USD', max_length=3)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of all orders', max_digits=15)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, help_text='Average profit margin %', max_digits=5)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('followup_date', models.DateTimeField(blank=True, null=True)),
                ('lead_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('conversion_probability', models.DecimalField(decimal_places=2, default=0, help_text='Conversion probability %', max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes not visible to client', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
                ('source', models.CharField(blank=True, help_text='How did they find us?', max_length=100, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=200, null=True)),
                ('marketing_campaign', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='crm/notes/')),
                ('is_private', models.BooleanField(default=False, help_text='Only visible to assigned team members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'In-Person Meeting'), ('video_call', 'Video Call'), ('visit', 'Site Visit'), ('quote', 'Quote Sent'), ('proposal', 'Proposal Sent'), ('order', 'Order Placed'), ('complaint', 'Complaint'), ('support', 'Support Request'), ('followup', 'Follow-up'), ('created', 'Record Created'), ('updated', 'Record Updated'), ('followup_completed', 'Follow-up Completed')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField()),
                ('outcome', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('no_response', 'No Response')], max_length=20, null=True)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('followup_notes', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('participants', models.CharField(blank=True, help_text='Other participants', max_length=500, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='crm/interactions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='Expected deal value', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='prospecting', max_length=20)),
                ('probability', models.IntegerField(default=10, help_text='Win probability %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('competitor', models.CharField(blank=True, max_length=200, null=True)),
                ('loss_reason', models.TextField(blank=True, help_text='Reason if deal is lost', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.deal')),
            ],
            options={
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status', 'customer_type'], name='crm_client_status_11c7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['country', 'city'], name='crm_client_country_c61865_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_to', 'status'], name='crm_client_assigne_536444_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_contacted'], name='crm_client_last_co_ac946a_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['client', 'interaction_type'], name='crm_custome_client__357040_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['next_followup'], name='crm_custome_next_fo_9d0beb_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['created_at'], name='crm_custome_created_891181_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['stage', 'assigned_to'], name='crm_deal_stage_858709_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['expected_close_date'], name='crm_deal_expecte_bc08a6_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['client', 'stage'], name='crm_deal_client__a52fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='crm_task_assigne_1d8686_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status'], name='crm_task_due_dat_2a3684_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['client', 'status'], name='crm_task_client__b81e3e_idx'),
        ),
    ]
