# Generated by Django 5.1.2 on 2025-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Default markup percentage for this client', max_digits=5),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('lay_bye', 'Lay Bye'), ('credit_terms', 'Credit Terms')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='quote_validity_days',
            field=models.IntegerField(default=30, help_text='Default quote validity period in days'),
        ),
        migrations.AddField(
            model_name='client',
            name='requires_quote_approval',
            field=models.BooleanField(default=False, help_text='Does this client require management approval for quotes?'),
        ),
        migrations.AlterField(
            model_name='customerinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'In-Person Meeting'), ('video_call', 'Video Call'), ('visit', 'Site Visit'), ('quote', 'Quote Sent'), ('proposal', 'Proposal Sent'), ('order', 'Order Placed'), ('complaint', 'Complaint'), ('support', 'Support Request'), ('followup', 'Follow-up'), ('created', 'Record Created'), ('updated', 'Record Updated'), ('followup_completed', 'Follow-up Completed'), ('quote_requested', 'Quote Requested'), ('quote_draft', 'Quote Draft Created'), ('quote_sent', 'Quote Sent to Client'), ('quote_viewed', 'Quote Viewed by Client'), ('quote_accepted', 'Quote Accepted'), ('quote_rejected', 'Quote Rejected'), ('quote_expired', 'Quote Expired'), ('quote_revised', 'Quote Revised')], max_length=50),
        ),
    ]
