# Generated by Django 5.1.2 on 2025-06-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_client_default_markup_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteraction',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
