# Generated by Django 5.1.2 on 2025-06-07 11:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_client_default_markup_percentage_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this quote', unique=True)),
                ('quote_number', models.CharField(help_text='Human-readable quote number (e.g., QUO-2024-0001)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Brief description of what this quote covers', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description or notes about this quote')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes not visible to client')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line items before tax', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Tax rate percentage', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated tax amount', max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overall discount percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated discount amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final amount after tax and discount', max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZWG', 'Zimbabwe Gold')], default='USD', max_length=3)),
                ('payment_terms', models.IntegerField(default=30, help_text='Payment terms in days')),
                ('delivery_terms', models.CharField(blank=True, help_text='Delivery terms and conditions', max_length=200)),
                ('validity_date', models.DateField(help_text='Quote expires on this date')),
                ('sent_date', models.DateTimeField(blank=True, help_text='When this quote was sent to client', null=True)),
                ('viewed_date', models.DateTimeField(blank=True, help_text='When client first viewed this quote', null=True)),
                ('response_date', models.DateTimeField(blank=True, help_text='When client responded (accepted/rejected)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved this quote (if approval required)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotes', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Employee responsible for this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='The client this quote is for', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crm.client')),
                ('created_by', models.ForeignKey(help_text='Employee who created this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description as it appears on quote', max_length=500)),
                ('detailed_specs', models.TextField(blank=True, help_text='Technical specifications for this item')),
                ('quantity', models.IntegerField(help_text='Quantity requested', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Quantity × Unit Price', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Our cost per unit', max_digits=10)),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Markup percentage applied', max_digits=5)),
                ('source_type', models.CharField(choices=[('stock', 'In Stock'), ('order', 'Order from Supplier'), ('direct', 'Direct from Supplier'), ('custom', 'Custom/Service Item')], default='stock', max_length=20)),
                ('supplier_lead_time', models.IntegerField(default=0, help_text='Lead time in days from supplier')),
                ('estimated_delivery', models.DateField(blank=True, help_text='When this item can be delivered', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this line item')),
                ('sort_order', models.IntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, help_text='Leave blank for custom items', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier for this item (if not from stock)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(default=1)),
                ('change_summary', models.TextField(help_text='What changed in this revision')),
                ('previous_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='quotes.quote')),
            ],
            options={
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('default_validity_days', models.IntegerField(default=30)),
                ('default_payment_terms', models.IntegerField(default=30)),
                ('template_items', models.JSONField(default=list, help_text='List of default items for this template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['client', 'status'], name='quotes_quot_client__badf70_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['created_at', 'status'], name='quotes_quot_created_6aad82_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['assigned_to', 'status'], name='quotes_quot_assigne_c1f7be_idx'),
        ),
    ]
